### ISSUE TITLE
Rotate a given array n times

### ISSUE THREAD

**Issue by Vivek-raj-gupta-2002** [adviksinghania/c-programs#16]
it will take an array, its size and an element to find in and then finds the element in the rotated array

Please assign it to me!!!!

**Comment by adviksinghania** [comment]
Can you give an example for this?

**Comment by jayprakash6547** [comment]
hi please assign this issue to me

**Comment by Vivek-raj-gupta-2002** [comment]
hii @adviksinghania ,
Like For example {1, 2, 3, 4, 5, 6, 7, 8, 9, 10} is an simple array
and if that array is rotated by 6 then{7, 8, 9, 10, 1, 2, 3, 4, 5, 6} is rotated array and searching in it by Binary search

**Comment by adviksinghania** [comment]
Binary search will require the array to be sorted and it can't be said that the rotated array will always be sorted.
Also, the element to be searched will be in the original array as well, so I don't understand why are we rotating and then searching?

**Comment by adviksinghania** [comment]
If you want, you can submit the code for rotating an array n times as in the first part of the example.

**Comment by Vivek-raj-gupta-2002** [comment]
so Actually the array is already given Rotated and then we are searching

**Comment by Vivek-raj-gupta-2002** [comment]
@adviksinghania ohk I can write the code for rotating the array only
Thanks!!

**Comment by Vivek-raj-gupta-2002** [comment]
Please Assign this task to me!!

**Comment by adviksinghania** [comment]
Go ahead, put the code in the Arrays folder.

**Comment by Vivek-raj-gupta-2002** [comment]
Nice to work with You!!
Thanks @adviksinghania
