### ISSUE TITLE
Write a C program to find the smallest missing element in a sorted array

### ISSUE THREAD

**Issue by Sarabjeet108** [adviksinghania/c-programs#2]
Example: nums[]=[1,2,4,5,6]
output: the smallest missing element is 3

**Comment by Yukino2002** [comment]
Hey, I would like to take up this issue.

**Comment by adviksinghania** [comment]
Go ahead @Sarabjeet108 you can make a new folder for arrays section.

**Comment by adviksinghania** [comment]
Hey @Yukino2002 you can take this issue as well since Sarabjeet hasn't submitted any PR yet.

**Comment by Vivek-raj-gupta-2002** [comment]
Can I do it !!!

**Comment by Sarabjeet108** [comment]
I have made the necessary changes required, kindly verify.
