### ISSUE TITLE
Write a C program to find the smallest and largest element in an array

### ISSUE THREAD

**Issue by Yukino2002** [adviksinghania/c-programs#3]

**Comment by adviksinghania** [comment]
Go ahead @Yukino2002 , you can make a program for smallest and largest element in an array. Put it in a folder named Arrays

**Comment by ayushigeorge** [comment]
I would like to contribute as well!

**Comment by adviksinghania** [comment]
Sorry but this issue has been resolved. If you have any other code you want to contribute, please open another issue.
